ramani-maps/ramani-maps

- .github/workflows/main.yml
- examples/annotation-simple/app/build.gradle
- examples/annotation-simple/settings.gradle
- examples/interactive-polygon/app/build.gradle
- examples/interactive-polygon/settings.gradle
* Stop using the composite build for annotation-plugin in the CI
* Have example default to ramani 0.1.1 from Maven (not composite build)
* Have the CI build the examples with raman from the repo, as a composite build
> Prepare ramani for 0.1.1 release

- .github/workflows/main.yml
- examples/annotation-simple/app/build.gradle
- examples/annotation-simple/app/src/main/java/org/ramani/example/annotation_simple/MainActivity.kt
- examples/annotation-simple/settings.gradle
The code is almost exactly the same as for ramani-maplibre, so the idea is to have one example with mapbox, and one with maplibre.
> Move annotation example to mapbox

- .github/workflows/main.yml
Now that we have two Maven artifacts (ramani-maplibre and ramani-mapbox), we can't really use the Github releases the same way. But I feel like we can just leverage tags, and that should be fine.
The alternative is to split them in two repos, but I'd like to keep them in the same repo if possible (seems like having two repos adds overhead and that's annoying).
> Add CI for ramani-mapbox

- ramani-mapbox/src/main/java/org/ramani/compose/CoordToPixelMapper.kt
- ramani-mapbox/src/main/java/org/ramani/compose/Polygon.kt
For some reason, Mapbox does not allow the coordinate to be outside the screen (but still on the map) when using [`pixelForCoordinates`](https://github.com/mapbox/mapbox-maps-android/blob/main/sdk/src/public/java/com/mapbox/maps/MapboxMap.kt#L795-L799):
```kotlin
return if (coordinate.x in 0.0..screenSize.width.toDouble() && coordinate.y in 0.0..screenSize.height.toDouble()) {
coordinate
} else {
ScreenCoordinate(-1.0, -1.0)
}
```
However, [`pixelsForCoordinates`](https://github.com/mapbox/mapbox-maps-android/blob/main/sdk/src/public/java/com/mapbox/maps/MapboxMap.kt#L820-L823) does what I would expect:
```kotlin
override fun pixelsForCoordinates(coordinates: List<Point>): List<ScreenCoordinate> {
checkNativeMap("pixelsForCoordinates")
return nativeMap.pixelsForCoordinates(coordinates)
} …
```
> mapbox: fix drag outside screen

- ramani-maplibre/src/main/java/org/ramani/compose/MapLibreCompose.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Utils.kt
Not needed anymore, we use the `keystore.properties` trick.
> maplibre: remove obsolete api key helper

- examples/interactive-polygon/app/src/main/java/org/ramani/example/interactive_polygon/MainActivity.kt
- ramani-maplibre/src/main/java/org/ramani/compose/CameraPositionState.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
The camera position is now saved even when the device orientation changes. Also it removes the need for the `neverEqualPolicy()`, which was a bit of a hack before :innocent:.
Before this fix, we can see that changing the device orientation resets the camera position (arguably difficult to see on those videos, but it's obvious when actually holding the devices :grin:):
https://github.com/ramani-maps/ramani-maps/assets/2606672/b0f8c10c-6098-4073-8082-e09d362d0c2b
After the fix, the camera position is saved across lifecycle changes:
https://github.com/ramani-maps/ramani-maps/assets/2606672/4844f803-a6d6-4c68-9b17-0bb9b1b7771b
> maplibre: Improve lifecycle for camera position

- ramani-maplibre/build.gradle
This brings [one minor fix of 2.0.2](https://github.com/maplibre/maplibre-plugins-android/releases/tag/v2.0.2):
* Fix dragging ordering (see [corresponding issue](https://github.com/maplibre/maplibre-plugins-android/issues/44))
> maplibre: update android-plugin-annotation-v9 to 2.0.2

- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
- ramani-maplibre/src/main/java/org/ramani/compose/UiSettings.kt
Adding UiSettings to MapLibre. Only CompassMargins for now, for testing, and because it is required by https://github.com/ramani-maps/ramani-maps/issues/39
> maplibre: add UiSettings (only CompassMargins for now)

- examples/location/app/src/main/java/org/ramani/example/location/MainActivity.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
This allows the user to get the device location by hoisting `userLocation`, such that the map will update it to the latest location.
In the location example, this is used with the "Center on device location" button.
> Expose user location

- ramani-maplibre/build.gradle
- ramani-maplibre/src/main/java/org/ramani/compose/CameraPositionState.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
Expose the different camera motion animations:
* INSTANT just "teleports" the camera to the new position (that was the behaviour until now).
* EASE gradually moves the camera over some duration (defined with `animationDurationMs`).
* FLY moves the camera with a transition that evokes a powered flight over some duration (defined with `animationDurationMs`).
At the same time I discovered the `kotlin-parcelize` plugin which makes it easier to implement `Parcelable`.
> maplibre: expose camera motion animations (ease and fly)

- examples/clusters/app/src/main/java/org/ramani/example/clusters/MainActivity.kt
- examples/custom-layers/app/src/main/java/org/ramani/example/custom_layers/MainActivity.kt
- examples/interactive-polygon/app/src/main/java/org/ramani/example/interactive_polygon/MainActivity.kt
- examples/location/app/src/main/java/org/ramani/example/location/MainActivity.kt
- ramani-maplibre/build.gradle
- ramani-maplibre/src/main/java/org/ramani/compose/CameraPositionState.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Circle.kt
- ramani-maplibre/src/main/java/org/ramani/compose/CircleWithItem.kt
- ramani-maplibre/src/main/java/org/ramani/compose/CoordToPixelMapper.kt
- ramani-maplibre/src/main/java/org/ramani/compose/DistanceBetweenCoords.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Fill.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibreCompose.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapProperties.kt
- ramani-maplibre/src/main/java/org/ramani/compose/PixelToCoordMapper.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Polygon.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Polyline.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Symbol.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Utils.kt
- ramani-maplibre/src/main/java/org/ramani/compose/VertexInsertCalculator.kt
Updated Maplibre to v11.0.0, which includes the fix for #66, and refactored the imports.
Tested successfully with the location and the interactive-polygon examples (at the moment, they use a composite instead of a direct implementation).
Resolves #66.
> Updated Maplibre to v11.0.0

- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
Support dynamic style urls as described in https://github.com/ramani-maps/ramani-maps/issues/73
I could use some help deciding how best to optimize for performance since changing the `styleUrl` should not reload everything in this `LaunchedEffect` .. im just a little unsure how to create a separate effect that only calls `map.setStyle(styleUrl)`
Resolves #73
> feat(styleUrl): add support for dynamic styleUrls

- README.md
- examples/annotation-simple/app/src/main/java/org/ramani/example/annotation_simple/MainActivity.kt
- examples/custom-layers/app/src/main/java/org/ramani/example/custom_layers/MainActivity.kt
- examples/interactive-polygon/app/src/main/java/org/ramani/example/interactive_polygon/MainActivity.kt
- examples/location/app/src/main/java/org/ramani/example/location/MainActivity.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibreCompose.kt
The `MapLibre` composable exposed a `styleUrl` until now. But this is limiting because users may want to get a `Style` from a JSON file instead of a URL to a JSON file.
This changes the interface of `MapLibre` such that it takes a `Style.Builder`. It is a breaking change, but it is trivial to adapt, e.g. from:
```
MapLibre(styleUrl = "path/to/style.json")
```
to
```
MapLibre(styleBuilder = Style.Builder().fromUri("path/to/style.json"))
```
Resolves #82.
> Expose Style.Builder instead of a styleUrl string

- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Polyline.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Symbol.kt
For polylines, this changes the isDashed parameter to a dash array, so the user can pass in the type of dash they wish to use. I also added an enum class with 3 basic line types with dash arrays provided.
For symbols, this exposes more icon & text parameters as well as the onDrag callback if the symbol is draggable.
This also adds a onMapClick callback to the MapLibre composable.
> Exposing more options for Polylines & Symbols

- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
- ramani-maplibre/src/main/java/org/ramani/compose/UiSettings.kt
This should fixe #88 by providing the `isLogoEnabled` setting and adds more settings from `org.maplibre.android.maps.UiSettings`.
Notes:
- I renamed `CompassMargins` to `Margins` to be able to use it for two more properties
- I made all the properties `val` to support stability in Compose
- Some settings are still missing as it's not trivial to add them to a class annotated with `@Parcelize`
* attributionDialogManager: AttributionDialogManager
* setFocalPoint(@Nullable focalPoint: PointF)
* setCompassImage(@NonNull compass: Drawable)
Resolves #88.
> feat(maplibre): Extend UiSettings with additional properties from MapLibre UiSettings

- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
This small PR moves the MapView creation outside of the MapLibre composable function, adding it as a parameter with a default value of rememberMapViewWithLifecycle(). This change provides more flexibility in map view management and allows for easier customization and reuse of the map view.
The modification doesn't change the functional behavior but improves the composable's design by making the map view more configurable.
> Refactor MapLibre: Move MapView to composable parameter

- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
This will allow to pass a custom `LocationEngine` to `MapLibre`. If the parameter is null, it will still use the default LocationEngine.
Resolves #96
> feat(maplibre): Support for setting custom LocationEngine

- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
I noticed that if I pass new sources, layers, or images to the `MapLibre` composable they won't be passed on to MapLibreMap. This means that I can never update these. Therefore I created this fix. 
Let me know if it makes sense or if it was on purpose that they are not passed as keys to the `LaunchedEffect`.
> Fix: Updated sources, layers, and images are not passed on to MapLibreMap

- examples/location/app/build.gradle.kts
- examples/location/app/src/main/java/org/ramani/example/location/MainActivity.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
Allow users to set the `CameraMode` for tracking location changes. CameraMode options and sdk information can be found [here](https://docs.mapbox.com/android/legacy/maps/guides/location-component/#cameramode).
Closes https://github.com/ramani-maps/ramani-maps/issues/72
> feat: add cameraMode options for tracking location changes

- ramani-maplibre/gradle/libs.versions.toml
This fixes a bug where symbols disappear when the map rotates.
> Update maplibre to 11.6.1 and annotation-plugin to 3.0.2

- ramani-maplibre/src/main/java/org/ramani/compose/CircleWithItem.kt
The recent change of having a default `imageId` has resulted in bug where using `CircleWithItem` renders a giant red marker when passing `imageId = null`
Example:
```
@Composable
fun LocationSymbol(item: LiveLocationShare) {
val location = Location.fromGeoUri(item.lastLocation.location.geoUri) ?: return
val latLng = LatLng(location.lat, location.lon)
CircleWithItem(
center = latLng,
radius = 10.0F,
isDraggable = false,
color = "#F6993A",
text = item.userId.toString(),
zIndex = 1,
itemSize = 12F,
borderColor = "#4A4A4A",
borderWidth = 3.0F,
imageId = null
)
}
```
> fix: a giant marker is being rendered when imageId is null

- examples/custom-layers/app/src/main/java/org/ramani/example/custom_layers/MainActivity.kt
- examples/location/app/src/main/java/org/ramani/example/location/MainActivity.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibreCompose.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Symbol.kt
This brings a bunch of improvements related to reloading the style and some location features.
@quentinus95, @torrybr: It would be useful if you could try this PR and let me know if it helps some of the issues you reported :pray:.
You should be able to just clone this branch somewhere on your system, and then in your app edit `settings.gradle.kts` to add:
```
includeBuild("/path/to/ramani-maps/ramani-maplibre")
```
This will tell gradle to use the local branch instead of pulling Ramani from Maven.
> Fix style reloading and location

- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
I think there is a bug where the MapProperties value passed to MapLibre isn't being properly applied. Without this the initial compose of the map doesn't respect anything defined in MapProperties.
I tested it locally and it works.
> Bugfix: Add MapProperties to MapPropertiesNode and apply it

- ramani-maplibre/build.gradle.kts
- ramani-maplibre/src/main/java/org/ramani/compose/Circle.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
- ramani-maplibre/src/main/java/org/ramani/compose/MapLibreCompose.kt
- ramani-maplibre/src/main/java/org/ramani/compose/Symbol.kt
Hi,
This is a PR which will add `onClick` and `onLongClick` callbacks to circles and symbols.
It works by adding click and long-click handlers to the `CircleManager` and then calling `onClick` and `onLongClick` callbacks provided as arguments to `MapLibre`.
To get it to work I needed to return `false`, rather than `true`, to the map's own click and long click listeners, otherwise the events are not propagated to the annotations.
The PR also adds a new `data` parameter to `Circle` and `Symbol`, allowing arbitrary data to be added to these annotations. These are of type `JsonElement`, matching what is expected by MapLibre's `CircleOptions` and `SymbolOptions`. The `onClick` and `onLongClick` event handlers then receives the data as a (nullable) parameter.
Additionally, to get Ramani to …
> Add clickable functionality and data to circles and symbols

- README.md
- README.openfreemap.md
- README.vulkan.md
Ramani Maps generally works nicely with the free maps provided by the [OpenFreeMap](https://openfreemap.org) project. On a real device there are no issues whatsoever, however on the Android emulator there appear to be some rendering problems with MapLibre Native in general (and hence Ramani Maps) when using recent versions of MapLibre Native 11.8.0+ (and hence Ramani versions 0.9.0+).
This is discussed in [issue #3648 of MapLibre Native](https://github.com/maplibre/maplibre-native/issues/3648) and appears to be due to OpenGL emulation issues. A suggested workaround in that issue is to use the Vulkan build of MapLibre Native instead, and this appears to work for me personally.
This PR adds a document describing the issue and the intended fix. I'm not sure if the ability to allow developers …
> [DOCS] Add docs on using OpenFreeMap with emulator
